import { CreateProductDto } from './dto/create-product.dto';

export const SEED_PRODUCTS: CreateProductDto[] = [
  {
    name: 'Sofá Ébano',
    description: 'Sofá de tres puestos en estructura de roble macizo, tapizado en lino natural color crema. Cojines independientes con relleno de pluma.',
    price: 4250000,
    stock: 8,
    category: 'salas',
    height: 85,
    width: 220,
    depth: 95,
    deliveryTime: '6 a 8 semanas',
    brandColor: 'berenjena',
    materials: ['Roble macizo', 'Lino natural', 'Pluma']
  },
  {
    name: 'Mesa de centro Roble',
    description: 'Mesa baja en madera de roble con acabado natural al aceite. Patas torneadas y bandeja inferior para revistas.',
    price: 1480000,
    stock: 15,
    category: 'salas',
    height: 45,
    width: 120,
    depth: 60,
    deliveryTime: '4 a 6 semanas',
    brandColor: 'mostaza',
    materials: ['Roble macizo', 'Aceite natural']
  },
  {
    name: 'Mecedora Junco',
    description: 'Mecedora artesanal con asiento tejido en junco natural y estructura curvada en cedro.',
    price: 980000,
    stock: 12,
    category: 'salas',
    height: 105,
    width: 60,
    depth: 90,
    deliveryTime: '5 a 7 semanas',
    brandColor: 'agua-marina',
    materials: ['Cedro', 'Junco tejido a mano']
  },
  {
    name: 'Mesa familiar Nogal',
    description: 'Mesa de comedor para ocho puestos en nogal americano, tablero de una sola pieza y patas trapezoidales.',
    price: 5200000,
    stock: 5,
    category: 'comedores',
    height: 75,
    width: 240,
    depth: 100,
    deliveryTime: '8 a 10 semanas',
    brandColor: 'berenjena',
    materials: ['Nogal americano', 'Cera de abejas']
  },
  {
    name: 'Sillas Tejido (set de 4)',
    description: 'Conjunto de cuatro sillas con estructura de cedro y respaldo tejido en cuerda algodón.',
    price: 2100000,
    stock: 10,
    category: 'comedores',
    height: 90,
    width: 45,
    depth: 50,
    deliveryTime: '6 a 8 semanas',
    brandColor: 'mostaza',
    materials: ['Cedro', 'Cuerda de algodón']
  },
  {
    name: 'Aparador Mostaza',
    description: 'Aparador de cuatro puertas en roble teñido con detalles en herraje de bronce envejecido.',
    price: 3380000,
    stock: 7,
    category: 'comedores',
    height: 90,
    width: 180,
    depth: 50,
    deliveryTime: '7 a 9 semanas',
    brandColor: 'agua-marina',
    materials: ['Roble teñido', 'Bronce envejecido']
  },
  {
    name: 'Cama doble Nido',
    description: 'Cama doble con cabecero acolchado en lino y estructura baja en madera de teca.',
    price: 3950000,
    stock: 6,
    category: 'dormitorios',
    height: 95,
    width: 160,
    depth: 210,
    deliveryTime: '7 a 9 semanas',
    brandColor: 'berenjena',
    materials: ['Teca', 'Lino natural']
  },
  {
    name: 'Mesa de noche Cedro',
    description: 'Mesa de noche compacta con un cajón y nicho inferior, en cedro con acabado mate.',
    price: 720000,
    stock: 20,
    category: 'dormitorios',
    height: 55,
    width: 45,
    depth: 40,
    deliveryTime: '4 a 6 semanas',
    brandColor: 'mostaza',
    materials: ['Cedro', 'Laca mate']
  },
  {
    name: 'Cómoda 4 cajones',
    description: 'Cómoda alta con cuatro cajones de cierre suave, tiradores de cuero y estructura en roble claro.',
    price: 2640000,
    stock: 9,
    category: 'dormitorios',
    height: 110,
    width: 90,
    depth: 50,
    deliveryTime: '6 a 8 semanas',
    brandColor: 'agua-marina',
    materials: ['Roble claro', 'Cuero curtido', 'Acero']
  }
];
